import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { BsFillMoonFill, BsFillSunFill, BsGithub } from 'react-icons/bs';
import { IoMoonOutline } from 'react-icons/io5';
import { useState } from 'react';
import Link from 'next/link';
import gt_roster from '../public/imgs/gt_roster.png';
import { Header } from '../components/Header';

export default function Home() {

  return (
    <div>
      <Head>
        <title>Feelsgladman Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-stone-900">
        <section className="h-max">
          <Header />

          <div className="max-w-2xl flex-column content-center items-center mx-auto">
            <p className="text-black text-md font-bold text-4xl pt-20 pb-5 dark:text-gray-200">
              Guardian Tales
            </p>
            <p className="text-black dark:text-gray-200 text-xl">
              Very cute 2D pixelized style gachapon game, with an excellent story mode and quite generous
              currency/gift/event system. Can feel plenty well playing this game with no spending, specially
              if you just wanna do the story mode and collect some waifus,
               which is probably the most fun you'll have in this game. Also, it has been released on Nintendo Switch
               recently, so if you rather play on that instead of your phone, well, you can. Oh and the controls are
               great! For mobile at least, can't say anything for the switch version since i didn't play that.
            </p>
            
            <p className="text-black dark:text-gray-200 text-xl pb-5 pt-5">
                Here's some videos from the official Guardian Tales yt channel:
            </p>
            <p className="text-black dark:text-gray-200 text-ml pb-5">Anime style game trailer</p>
            <iframe width="600" height="300" src="https://www.youtube.com/embed/1ATLebaVJvY" title="Guardian Tales | Anime Opening Style Trailer" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
            <p className="text-black dark:text-gray-200 text-ml pt-5 pb-5">Season 2 trailer</p>
            <iframe width="600" height="300" src="https://www.youtube.com/embed/c2h-yMKEOJo" title="Guardian Tales | Season 2 Trailer" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
            <p className="text-black dark:text-gray-200 text-ml pt-5 pb-5">Title screen (i love the title screen for some reason)</p>
            <iframe width="600" height="300" src="https://www.youtube.com/embed/kutnPmRSsaU" title="Title | Guardian Tales OST" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
            <p className="text-black dark:text-gray-200 text-xl pt-10 pb-5">
              And here's a screenie of my roster (just so you can see some of the artwork and models):
            </p>
            <Image className="pb-10"src={gt_roster} alt="gt_roster"/>
          </div>
        </section>
      </main>
    </div>
  )
}