import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { BsFillMoonFill, BsFillSunFill, BsGithub } from 'react-icons/bs';
import { IoMoonOutline } from 'react-icons/io5';
import { useState } from 'react';
import Link from 'next/link';

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? 'dark': ''}>
      <Head>
        <title>Feelsgladman Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-stone-900">
        <section className="h-max">
        <nav className="shadow-xl bg-stone-200 text-xl py-10 px-20 dark:text-white dark:bg-stone-800">
            <div className="flex max-w-2xl justify-between mx-auto">
              <h1 className="text-4xl text-transparent bg-clip-text bg-gradient-to-r from-green-700 to-green-500 font-bold">Feelsgladman</h1>
              <div className="flex items-center content-center gap-5">
                  <Link href="/" className="hover:text-gray-700 dark:hover:text-gray-200">Home</Link>
                  <button onClick={() => setDarkMode(!darkMode)} className="cursor-pointer">
                    <IoMoonOutline size="30"/>
                  </button>              
                  <a href="https://github.com/k7inho6" target="_blank"><BsGithub size='30'/></a>
              </div>
            </div>
          </nav>

          <div className="max-w-2xl flex-column content-center items-center mx-auto">
            <p className="text-black text-md font-bold text-4xl pt-20 pb-5 dark:text-gray-200">
              Overwatch 2
            </p>
            <p className="text-black dark:text-gray-200 text-xl">
              I mean... It's Overwatch... You probably know about this game, FPS with a lot
              of champions/skills and movement, woohoo, pewpew boomboom everywhere.
            </p>
            <p className="text-black dark:text-gray-200 text-xl pb-5 pt-5">
              I recently started getting into it with some friends, and am having quite some fun.
              Definitely a nice game to play <p className="underline inline italic">with friends.</p> Unfortunately
              i suck and am a newbie tho, so not much to talk about my performance or experience :^)
            </p>
            <p className="text-black dark:text-gray-200 text-xl pb-5 pt-5">
                Anyway, here's some nice OW gameplay vids from yt:
            </p>
            <iframe width="600" height="300" src="https://www.youtube.com/embed/i3fQncmSH_4" title="Hero Moments: Sayaplayer" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
            <iframe className="pt-5" width="600" height="300" src="https://www.youtube.com/embed/nKx5A_m2Qzo" title="Hero Moments: Profit" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
            <p className="text-black dark:text-gray-200 text-xl pt-5 pb-5">
              (Yes i know they are OW 1 vids, but it's basically the same game)
            </p>
          </div>
        </section>
      </main>
    </div>
  )
}